spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test_db
      host: localhost
      port: 27017
      database: test_db
      authentication-database: admin
      auto-index-creation: true


mongock:
  #  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

